services:
    netgen.enhanced_selection.search.solr.criterion_visitor.enhanced_selection:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\Search\Solr\Query\CriterionVisitor\EnhancedSelection
        arguments:
            - "@Ibexa\\Core\\Search\\Common\\FieldNameResolver"
            - "@Ibexa\\Contracts\\Core\\Search\\Field"
        tags:
            - { name: ibexa.search.solr.query.content.criterion.visitor }
            - { name: ibexa.search.solr.query.location.criterion.visitor }
